# Generated by Django 2.2 on 2020-10-17 10:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='amount',
            new_name='amount_paid',
        ),
    ]
