# Generated by Django 2.2 on 2020-10-30 18:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0007_librarybranch_activesub'),
        ('owner', '0002_auto_20201017_1625'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerSubscription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('days', models.PositiveSmallIntegerField()),
                ('startdate', models.DateField(auto_now_add=True)),
                ('enddate', models.DateField()),
                ('branchesAllowed', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveSmallIntegerField()),
                ('activeBranch', models.ManyToManyField(to='library.LibraryBranch')),
                ('onwer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='owner.Owner')),
            ],
            options={
                'verbose_name_plural': 'Owner Subscription',
            },
        ),
        migrations.CreateModel(
            name='Ownerpayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_id', models.CharField(max_length=100)),
                ('amount_paid', models.PositiveIntegerField()),
                ('paymentmode', models.CharField(default='Razor Pay', max_length=50)),
                ('subscription', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='owner.OwnerSubscription')),
            ],
            options={
                'verbose_name_plural': 'Owner Payment',
            },
        ),
    ]
