# Generated by Django 2.2 on 2020-10-30 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_ownerpayment_ownersubscription'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ownersubscription',
            old_name='onwer',
            new_name='owner',
        ),
    ]
