# Generated by Django 2.2 on 2020-10-30 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_auto_20201031_0002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownersubscription',
            name='enddate',
            field=models.DateField(blank=True, null=True),
        ),
    ]
