# Generated by Django 2.2 on 2020-10-31 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0005_auto_20201031_0004'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='basicSetup',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ownersubscription',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
