# Generated by Django 2.2 on 2020-11-02 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0006_auto_20201101_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownersubscription',
            name='order_id',
            field=models.CharField(blank=True, max_length=64, null=True),
        ),
        migrations.AddField(
            model_name='ownersubscription',
            name='purchased',
            field=models.BooleanField(default=False),
        ),
    ]
