# Generated by Django 2.2 on 2020-11-02 19:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0007_librarybranch_activesub'),
        ('owner', '0007_auto_20201103_0036'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerSubscriptionPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True)),
                ('days', models.PositiveSmallIntegerField()),
                ('startdate', models.DateField(auto_now_add=True)),
                ('enddate', models.DateField(blank=True, null=True)),
                ('branchesAllowed', models.PositiveSmallIntegerField()),
                ('amount', models.PositiveSmallIntegerField()),
                ('order_id', models.CharField(blank=True, max_length=64, null=True)),
                ('purchased', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=False)),
                ('activeBranch', models.ManyToManyField(to='library.LibraryBranch')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='owner.Owner')),
            ],
            options={
                'verbose_name_plural': 'Owner Subscription',
            },
        ),
        migrations.AlterField(
            model_name='ownerpayment',
            name='subscription',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='owner.OwnerSubscriptionPlan'),
        ),
        migrations.DeleteModel(
            name='OwnerSubscription',
        ),
        migrations.AddField(
            model_name='owner',
            name='active_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='owner_sub', to='owner.OwnerSubscriptionPlan'),
        ),
    ]
