# Generated by Django 2.2 on 2020-11-03 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_auto_20201103_0113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='branches',
            field=models.ManyToManyField(blank=True, to='library.LibraryBranch'),
        ),
        migrations.AlterField(
            model_name='owner',
            name='branches',
            field=models.ManyToManyField(blank=True, to='library.LibraryBranch'),
        ),
    ]
