# Generated by Django 2.2 on 2020-11-13 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0009_auto_20201103_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownersubscriptionplan',
            name='activeBranch',
            field=models.ManyToManyField(blank=True, to='library.LibraryBranch'),
        ),
    ]
