# Generated by Django 2.2 on 2020-11-15 20:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_auto_20201113_1646'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerDevice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_id', models.CharField(max_length=256, unique=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='owner.Owner')),
            ],
            options={
                'verbose_name_plural': 'Owner Devices',
            },
        ),
    ]
