# Generated by Django 2.2 on 2020-11-18 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0011_ownerdevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='reponse',
            field=models.TextField(default=''),
        ),
    ]
