# Generated by Django 2.2 on 2020-11-19 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0012_feedback_reponse'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerSubPlan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_name', models.CharField(max_length=256)),
                ('amount', models.PositiveIntegerField()),
                ('extra', models.PositiveIntegerField()),
                ('days', models.PositiveIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Owner Subscription Plans',
            },
        ),
    ]
