# Generated by Django 2.2 on 2020-11-11 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_notifications'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='faq',
            options={'verbose_name_plural': 'Frequently Asked Questions'},
        ),
        migrations.AddField(
            model_name='faq',
            name='user_type',
            field=models.CharField(choices=[('Student', 'Student'), ('Owner', 'Owner'), ('Employee', 'Employee')], default='student', max_length=16),
            preserve_default=False,
        ),
    ]
