# Generated by Django 2.2 on 2020-11-17 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_mydevice'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='incident',
            name='ticket',
            field=models.CharField(default=False, max_length=126),
            preserve_default=False,
        ),
    ]
