# Generated by Django 2.2 on 2020-11-18 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20201117_1802'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='inactive',
            field=models.BooleanField(default=False),
        ),
    ]
