# Generated by Django 2.2 on 2020-10-22 19:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0004_auto_20201021_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='Studentpaymentorder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.PositiveSmallIntegerField()),
                ('order_id', models.CharField(blank=True, max_length=128, null=True)),
                ('payment_id', models.CharField(blank=True, max_length=128, null=True)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Student')),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
    ]
