# Generated by Django 2.2 on 2020-10-29 15:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ubfcore', '0003_delete_promocode'),
        ('student', '0006_auto_20201029_1936'),
        ('ubfquiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=128)),
                ('payment_id', models.CharField(max_length=128)),
                ('date_time', models.DateTimeField(auto_now_add=True)),
                ('success', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Promocode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=7, unique=True)),
                ('title', models.CharField(default='', max_length=100)),
                ('description', models.TextField(default='')),
                ('discountpercent', models.FloatField(blank=True, null=True)),
                ('max_discount', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('validity', models.DateField(blank=True, null=True)),
                ('createdOn', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'UBF promocodes',
            },
        ),
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('ordered_date', models.DateTimeField(blank=True, null=True)),
                ('ordered', models.BooleanField(default=False)),
                ('order_id', models.CharField(max_length=64, unique=True)),
                ('single_product', models.BooleanField(default=False)),
                ('codetype', models.CharField(blank=True, max_length=10, null=True)),
                ('amount', models.PositiveIntegerField(blank=True, null=True)),
                ('mcqs', models.ManyToManyField(blank=True, to='ubfcore.MCQ')),
                ('payment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ubfcart.Payment')),
                ('pdfs', models.ManyToManyField(blank=True, to='ubfcore.PDF')),
                ('promocode', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='ubfcart.Promocode')),
                ('sessions', models.ManyToManyField(blank=True, to='ubfcore.Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Student')),
                ('summaries', models.ManyToManyField(blank=True, to='ubfcore.Summary')),
                ('tests', models.ManyToManyField(blank=True, to='ubfquiz.Quiz')),
            ],
            options={
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='SaveForLater',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcqs', models.ManyToManyField(blank=True, to='ubfcore.MCQ')),
                ('pdfs', models.ManyToManyField(blank=True, to='ubfcore.PDF')),
                ('sessions', models.ManyToManyField(blank=True, to='ubfcore.Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Student')),
                ('summaries', models.ManyToManyField(blank=True, to='ubfcore.Summary')),
                ('tests', models.ManyToManyField(blank=True, to='ubfquiz.Quiz')),
            ],
            options={
                'verbose_name_plural': 'Saved For Later',
            },
        ),
        migrations.CreateModel(
            name='Bookmark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcqs', models.ManyToManyField(blank=True, to='ubfcore.MCQ')),
                ('pdfs', models.ManyToManyField(blank=True, to='ubfcore.PDF')),
                ('sessions', models.ManyToManyField(blank=True, to='ubfcore.Session')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Student')),
                ('summaries', models.ManyToManyField(blank=True, to='ubfcore.Summary')),
                ('tests', models.ManyToManyField(blank=True, to='ubfquiz.Quiz')),
            ],
            options={
                'verbose_name_plural': 'Bookmarks',
            },
        ),
    ]
