# Generated by Django 2.2 on 2020-11-02 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0003_rewardsystem_totalreferral'),
        ('ubfcart', '0002_auto_20201101_0048'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usercart',
            name='codetype',
        ),
        migrations.AddField(
            model_name='usercart',
            name='rewardcode',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='reward.RewardCode'),
        ),
    ]
