# Generated by Django 2.2 on 2020-11-19 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubfcart', '0003_auto_20201102_2233'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
    ]
