# Generated by Django 2.2 on 2020-10-19 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('student', '0002_auto_20201019_1106'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
            ],
            options={
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='GeneralNotification',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=250)),
                ('description', models.TextField()),
                ('link', models.URLField(blank=True, default='')),
                ('rollOut', models.BooleanField(default=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'General Notification',
            },
        ),
        migrations.CreateModel(
            name='MCQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
                ('preview_file', models.FileField(upload_to='')),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'MCQs',
            },
        ),
        migrations.CreateModel(
            name='PDF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('file', models.FileField(upload_to='')),
                ('price', models.PositiveSmallIntegerField(default=0)),
            ],
            options={
                'verbose_name_plural': 'PDFs',
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=6)),
                ('percent', models.PositiveSmallIntegerField()),
                ('description', models.TextField(blank=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name_plural': 'Promo Codes',
            },
        ),
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=128)),
                ('date', models.DateField()),
                ('demo', models.FileField(blank=True, null=True, upload_to='')),
                ('video', models.FileField(blank=True, null=True, upload_to='')),
                ('youtube_link', models.CharField(blank=True, max_length=512, null=True)),
                ('price', models.PositiveSmallIntegerField()),
            ],
            options={
                'verbose_name_plural': 'Sessions',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubfcore.Category')),
            ],
            options={
                'verbose_name_plural': 'Sub-Categories',
            },
        ),
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('description', models.TextField()),
                ('file', models.FileField(upload_to='')),
                ('image', models.ImageField(upload_to='')),
                ('preview_file', models.FileField(upload_to='')),
                ('price', models.PositiveSmallIntegerField(default=0)),
                ('mcq', models.ManyToManyField(null=True, to='ubfcore.MCQ')),
                ('sub_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubfcore.SubCategory')),
            ],
            options={
                'verbose_name_plural': 'Summaries',
            },
        ),
        migrations.CreateModel(
            name='UserSubscriptions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mcqs', models.ManyToManyField(blank=True, to='ubfcore.MCQ')),
                ('pdfs', models.ManyToManyField(blank=True, to='ubfcore.PDF')),
                ('sessions', models.ManyToManyField(blank=True, to='ubfcore.Session')),
                ('student', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='student.Student')),
                ('summaries', models.ManyToManyField(blank=True, to='ubfcore.Summary')),
            ],
            options={
                'verbose_name_plural': 'Student Subscriptions',
            },
        ),
        migrations.AddField(
            model_name='pdf',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubfcore.SubCategory'),
        ),
        migrations.AddField(
            model_name='mcq',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ubfcore.SubCategory'),
        ),
    ]
