# Generated by Django 2.2 on 2020-10-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubfquiz', '0001_initial'),
        ('ubfcore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersubscriptions',
            name='tests',
            field=models.ManyToManyField(blank=True, to='ubfquiz.Quiz'),
        ),
    ]
