# Generated by Django 2.2 on 2020-10-28 09:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ubfcore', '0002_usersubscriptions_tests'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PromoCode',
        ),
    ]
