# Generated by Django 2.2 on 2020-10-29 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ubfcore', '0003_delete_promocode'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=512)),
                ('image', models.ImageField(upload_to='')),
                ('date', models.DateField()),
                ('content', models.TextField()),
            ],
            options={
                'verbose_name_plural': 'Articles',
            },
        ),
    ]
