# Generated by Django 2.2 on 2020-10-28 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('library', '0006_auto_20201028_1456'),
        ('student', '0004_auto_20201021_2230'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentUBFPayment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='', max_length=200)),
                ('amount_paid', models.PositiveSmallIntegerField()),
                ('date', models.DateField(auto_now_add=True)),
                ('payment_mode', models.CharField(default='Razor Pay', max_length=20)),
                ('type', models.CharField(max_length=20)),
                ('libraryBranch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='library.LibraryBranch')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='student.Student')),
            ],
        ),
    ]
