# Generated by Django 2.2 on 2020-10-31 19:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_auto_20201029_1936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasedsubscription',
            name='locker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='library.LibraryLocker'),
        ),
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Not Specified', 'Not Specified')], max_length=20),
        ),
        migrations.AlterField(
            model_name='studentpayment',
            name='purchased_subscription',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='student.PurchasedSubscription'),
        ),
    ]
