# Generated by Django 2.2 on 2020-11-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0007_auto_20201101_0048'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchasedsubscription',
            name='usage50',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='purchasedsubscription',
            name='usage85',
            field=models.BooleanField(default=False),
        ),
    ]
