# Generated by Django 2.2 on 2020-11-02 17:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0008_auto_20201102_1550'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentofftime',
            name='slot',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='timeslot', to='core.TimeSlot'),
        ),
    ]
