# Generated by Django 2.2 on 2020-11-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0009_auto_20201102_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='referral_code',
            field=models.CharField(default='HELLO', max_length=8),
            preserve_default=False,
        ),
    ]
