# Generated by Django 2.2 on 2020-10-29 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardcode',
            name='claimed',
            field=models.BooleanField(default=False),
        ),
    ]
