# Generated by Django 2.2 on 2020-10-30 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reward', '0002_rewardcode_claimed'),
    ]

    operations = [
        migrations.AddField(
            model_name='rewardsystem',
            name='totalReferral',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
